<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '7b11c4dc42b3b3023073cb14e519683c' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'e5c549289a364910535a9d3f40556cd3' => $baseDir . '/includes/Helpers/petition_functions.php',
    '1365a2f3a29db2f30d4f6cae3c7ecc93' => $baseDir . '/includes/Helpers/petition_tpl_loader.php',
    '8c0b3aaf70332647929783c1deb90d57' => $baseDir . '/includes/Helpers/CBXPetitionEmailFunctions.php',
);
